=== NamizataS/C-project/Part3/recipe.dtd
<!DOCTYPE RECIPE[
        <!ELEMENT recipe (cake+,pie*)>
        <!ELEMENT cake (ingrediends+)>
        <!ELEMENT pie (#PCDATA)>
        <!ELEMENT ingrediends (#PCDATA)>

        <!ATTLIST cake name CDATA #REQUIRED>
        <!ATTLIST ingrediends quantity CDATA #IMPLIED>

        ]>

=== NamizataS/C-project/Part3/recipe.xml
<?xml version="1.0" encoding="UTF-8" ?>

<!DOCTYPE recipe SYSTEM "recipe.dtd"[]>

<recipe category="cake">
    <cake name="Fraisiers">
        <ingrediends>Flour</ingrediends>
        <ingrediends>Eggs</ingrediends>
        <ingrediends>Strawberry</ingrediends>
    </cake>
    <pie name="Tarte aux pommes">
        <ingrediends>Flour</ingrediends>
        <ingrediends>Eggs</ingrediends>
        <ingrediends>Apple</ingrediends>
    </pie>
</recipe>
